/**
 * Copyright (C) 2008 Peter Butterfill.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.butterfill.opb.util.OpbToStringHelper;
import com.butterfill.opb.util.OpbToStringMode;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import junit.framework.*;
/*
 * RootSuite.java
 * JUnit based test
 *
 * Created on 02 September 2007, 13:11
 */

/**
 *
 * @author Peter Butterfill
 */
public class RootSuite extends TestCase {
    
    public RootSuite(String testName) {
        super(testName);
    }

    @Override
    protected void setUp() throws Exception {
    }

    @Override
    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() throws Exception {
//        OpbToStringHelper.setToStringMode(OpbToStringMode.FULL);
        
//        Logger.getLogger("").setLevel(Level.ALL);
//        FileHandler fileHandler = new FileHandler();
//        fileHandler.setLevel(Level.ALL);
//        Logger.getLogger("").addHandler(fileHandler);
        
        TestSuite suite = new TestSuite("RootSuite");
        suite.addTest(com.ComSuite.suite());
        return suite;
    }
    
}
