/**
 * Copyright (C) 2008 Peter Butterfill.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.butterfill.opb.groups;

import junit.framework.*;

/**
 *
 * @author Peter Butterfill
 */
public class GroupsSuite extends TestCase {
    
    public GroupsSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("GroupsSuite");
        suite.addTest(com.butterfill.opb.groups.OpbManyMembersGroupTest.suite());
        suite.addTest(com.butterfill.opb.groups.OpbGroupMemberWrapperTest.suite());
        suite.addTest(com.butterfill.opb.groups.OpbGroupManagerMapTest.suite());
        suite.addTest(com.butterfill.opb.groups.OpbGroupManagerTest.suite());
        suite.addTest(com.butterfill.opb.groups.OpbGroupTest.suite());
        suite.addTest(com.butterfill.opb.groups.OpbGroupableTest.suite());
        suite.addTest(com.butterfill.opb.groups.OpbSingleMemberGroupTest.suite());
        suite.addTest(com.butterfill.opb.groups.OpbGroupMemberWrapperImplTest.suite());
        return suite;
    }
    
}
