/**
 * Copyright (C) 2008 Peter Butterfill.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.butterfill.opb.timing;

import junit.framework.*;

/**
 *
 * @author Peter Butterfill
 */
public class TimingSuite extends TestCase {
    
    public TimingSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("TimingSuite");
        suite.addTest(com.butterfill.opb.timing.OpbBasicTimingEventListenerTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbTimingEventListenerTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbTimingEventAggregateHelperTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbTimingEventTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbEventTimerTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbTimingEventAggregateTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbEventTimerProviderTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbTimingEventPublisherTest.suite());
        suite.addTest(com.butterfill.opb.timing.OpbBasicTimingEventListenerConcurrentTest.suite());
        return suite;
    }
    
}
