/**
 * Copyright (C) 2008 Peter Butterfill.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.butterfill.opb.util;

import junit.framework.*;

/**
 *
 * @author Peter Butterfill
 */
public class UtilSuite extends TestCase {
    
    public UtilSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("UtilSuite");
        suite.addTest(com.butterfill.opb.util.OpbValueWrapperTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbValueWrapperImplTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbExceptionHelperTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbToStringHelperTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbComparisonHelperTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbWorkingObjectListWrapperTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbToStringModeTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbExactMatchListTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbAssertTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbBooleanHelperTest.suite());
        suite.addTest(com.butterfill.opb.util.OpbScalarResultCacheTest.suite());
        return suite;
    }
    
}
